import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaAws,
  FaFigma,
  FaGoogle,
  FaFacebook,
  FaMailchimp,
  FaPython,
  FaJava,
  FaPhp,
  FaAngular,
  FaVuejs,
} from "react-icons/fa";
import {
  SiMongodb,
  SiFirebase,
  SiCanva,
  SiHubspot,
  SiHotjar,
  SiPostgresql,
  SiLinkedin,
  SiAdobe,
  SiFlutter,
  SiJavascript,
  SiTypescript,
  SiDjango,
} from "react-icons/si";
import { TbBrandReactNative } from "react-icons/tb";

export const techLogos = [
  { icon: FaReact, name: "React" },
  { icon: TbBrandReactNative, name: "React Native" },
  { icon: FaNodeJs, name: "Node.js" },
  { icon: SiJavascript, name: "JavaScript" },
  { icon: SiTypescript, name: "TypeScript" },
  { icon: FaPython, name: "Python" },
  { icon: SiDjango, name: "Django" },
  { icon: FaJava, name: "Java" },
  { icon: FaPhp, name: "PHP" },
  { icon: SiFlutter, name: "Flutter" },
  { icon: FaDocker, name: "Docker" },
  { icon: FaAws, name: "AWS" },
  { icon: SiFirebase, name: "Firebase" },
  { icon: SiMongodb, name: "MongoDB" },
  { icon: SiPostgresql, name: "PostgreSQL" },
  { icon: FaAngular, name: "Angular" },
  { icon: FaVuejs, name: "Vue.js" },
  { icon: FaFigma, name: "Figma" },
  { icon: SiCanva, name: "Canva" },
];

export const marketingLogos = [
  { icon: FaGoogle, name: "Google Ads" },
  { icon: FaFacebook, name: "Facebook Ads" },
  { icon: SiLinkedin, name: "LinkedIn Ads" },
  { icon: FaMailchimp, name: "Mailchimp" },
  { icon: SiHubspot, name: "HubSpot" },
  { icon: SiHotjar, name: "Hotjar" },
  { icon: FaFigma, name: "Figma" },
  { icon: SiCanva, name: "Canva" },
  { icon: SiAdobe, name: "Adobe CC" },
];
